name: API Tests

on: [push, pull_request]

jobs:
  test-api:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Start flask app
        env:
          MONGO_HOST: localhost
          PYTHONPATH: ${{ github.workspace }}
          FLASK_APP: api.py
        run: |
          nohup flask run > flask.log 2>&1 &
          echo "Waiting for Flask to start..."
          sleep 5

      - name: Check Flask logs (debug)
        if: always()
        run: cat flask.log

      - name: Run Unit Tests (including Repository Mock tests)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python3 -m pytest tests/test_repository.py 
          # python3 -m pytest tests/test_*.py

      - name: Run API Integration Tests
        env:
          MONGO_HOST: localhost
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python3 -m pytest tests/api

      - name: Run BDD Tests
        env:
           MONGO_HOST: localhost
           PYTHONPATH: ${{ github.workspace }}
        run: behave