name: Unit tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest coverage pymongo
          
          REQ_FILE=$(find . -name requirements.txt | head -n 1)
          if [ -n "$REQ_FILE" ]; then 
            pip install -r "$REQ_FILE"
          fi

      - name: Run Lint and Tests (Auto-Locate)
        run: |
          SRC_DIR=$(find . -type d -name "src" | head -n 1)
          
          if [ -z "$SRC_DIR" ]; then
             exit 1
          fi
          
          APP_ROOT=$(dirname "$SRC_DIR")
          
          cd "$APP_ROOT"
          export PYTHONPATH=$(pwd)

          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

          python3 -m coverage run --source=src --omit=api.py -m pytest -k "not api and not perf"

      - name: Show coverage
        run: |
          SRC_DIR=$(find . -type d -name "src" | head -n 1)
          APP_ROOT=$(dirname "$SRC_DIR")
          cd "$APP_ROOT"
          
          python3 -m coverage report -m

      - name: Check coverage threshold
        run: |
          SRC_DIR=$(find . -type d -name "src" | head -n 1)
          APP_ROOT=$(dirname "$SRC_DIR")
          cd "$APP_ROOT"
          
          python3 -m coverage report --fail-under=100
